class SBError:
    description: str
    fail: bool
    success: bool
    type: int
    value: int

    def Clear(self): ...

    def Fail(self) -> bool: ...

    def GetCString(self) -> str: ...

    def GetDescription(self, description: 'SBStream') -> bool: ...

    def GetError(self) -> int: ...

    def GetType(self) -> int: ...

    def IsValid(self) -> bool: ...

    def SetError(self, err: int, type: int): ...

    def SetErrorString(self, format: str, str1: str = None, str2: str = None, str3: str = None) -> int: ...

    def SetErrorToErrno(self): ...

    def SetErrorToGenericError(self): ...

    def Success(self) -> bool: ...