from .SBType import SBType


class SBTypeList:
    def Append(self, entry: SBType): ...

    def GetSize(self) -> int: ...

    def GetTypeEnumMemberAtIndex(self, index: int) -> SBType: ...

    def IsValid(self) -> bool: ...