from .SBTypeEnumMember import SBTypeEnumMember


class SBTypeEnumMemberList:
    def Append(self, entry: SBTypeEnumMember): ...

    def GetSize(self) -> int: ...

    def GetTypeEnumMemberAtIndex(self, index: int) -> SBTypeEnumMember: ...

    def IsValid(self) -> bool: ...