from typing import List, Union

from .SBAddress import SBAddress
from .SBData import SBData
from .SBError import SBError
from .SBExpressionOptions import SBExpressionOptions
from .SBFrame import SBFrame
from .SBProcess import SBProcess
from .SBTarget import SBTarget
from .SBType import SBType


class SBValue:
    addr: SBAddress
    address_of: 'SBValue'
    changed: bool
    child: List[str]
    children: List['SBValue']
    data: SBData
    deref: 'SBValue'
    description: str
    dynamic: 'SBValue'
    error: SBError
    format: int
    frame: SBFrame
    is_in_scope: bool
    load_addr: int
    location: str
    name: str
    num_children: int
    path: str
    process: SBProcess
    signed: int
    size: int
    summary: str
    target: SBTarget
    thread: 'SBThread'
    type: SBType
    unsigned: int
    value: str
    value_type: int

    def __iter__(self): ...

    def __next__(self) -> 'SBValue': ...

    def AddressOf(self) -> 'SBValue': ...

    def Cast(self, type: SBType) -> 'SBValue': ...

    def Clear(self): ...

    def Clone(self) -> 'SBValue': ...

    def CreateChildAtOffset(self, name: str, offset: int, type: SBType) -> 'SBValue': ...

    def CreateValueFromAddress(self, name: str, address: int, type: SBType) -> 'SBValue': ...

    def CreateValueFromData(self, name: str, data: SBData, type: SBType) -> 'SBValue': ...

    def CreateValueFromExpression(self, name: str, expression: str) -> 'SBValue': ...

    def Dereference(self) -> 'SBValue': ...

    def EvaluateExpression(self, expr: str, options: SBExpressionOptions = None, name: str = None) -> 'SBValue': ...

    def GetAddress(self) -> 'SBAddress': ...

    def GetByteSize(self) -> int: ...

    def GetChildAtIndex(self, idx: int, use_dynamic: int = None, can_create_synthetic: bool = False) -> 'SBValue': ...

    def GetChildMemberWithName(self, name: str, use_dynamic: int = None) -> 'SBValue': ...

    def GetData(self) -> 'SBData': ...

    def GetDeclaration(self) -> 'GetDeclaration': ...

    def GetDescription(self, description: 'SBStream') -> bool: ...

    def GetDisplayTypeName(self) -> str: ...

    def GetDynamicValue(self, use_dynamic: int = None) -> 'SBValue': ...

    def GetError(self) -> SBError: ...

    def GetExpressionPath(self, description: 'SBStream', qualify_cxx_base_classes: bool = False) -> 'SBValue': ...

    def GetFormat(self) -> int: ...

    def GetFrame(self) -> SBFrame: ...

    def GetID(self) -> int: ...

    def GetIndexOfChildWithName(self, name: str) -> int: ...

    def GetLoadAddress(self) -> int: ...

    def GetLocation(self) -> str: ...

    def GetName(self) -> str: ...

    def GetNonSyntheticValue(self) -> 'SBValue': ...

    def GetNumChildren(self, max: int = None) -> int: ...

    def GetObjectDescription(self) -> str: ...

    def GetPointeeData(self, item_idx: int = 0, item_count: int = 1) -> SBData: ...

    def GetPreferDynamicValue(self) -> int: ...

    def GetPreferSyntheticValue(self) -> bool: ...

    def GetProcess(self) -> SBProcess: ...

    def GetStaticValue(self) -> 'SBValue': ...

    def GetSummary(self, stream: 'SBStream' = None, options: 'SBTypeSummaryOptions' = None) -> str: ...

    def GetTarget(self) -> SBTarget: ...

    def GetThread(self) -> 'SBThread': ...

    def GetType(self) -> SBType: ...

    def GetTypeFilter(self) -> 'SBTypeFilter': ...

    def GetTypeFormat(self) -> 'SBTypeFormat': ...

    def GetTypeName(self) -> str: ...

    def GetTypeSummary(self) -> 'SBTypeSummary': ...

    def GetTypeSynthetic(self) -> 'SBTypeSynthetic': ...

    def GetVTable(self) -> 'SBValue': ...

    def GetValue(self) -> str: ...

    def GetValueAsSigned(self, err_of_fail_value: Union[SBError, int] = None, fail_value=0) -> int: ...

    def GetValueAsUnsigned(self, err_of_fail_value: Union[SBError, int] = None, fail_value=0) -> int: ...

    def GetValueDidChange(self) -> bool: ...

    def GetValueForExpressionPath(self, expr_path: str) -> 'SBValue': ...

    def GetValueType(self) -> int: ...

    def IsDynamic(self) -> bool: ...

    def IsInScope(self) -> bool: ...

    def IsRuntimeSupportValue(self) -> bool: ...

    def IsSynthetic(self) -> bool: ...

    def IsSyntheticChildrenGenerated(self) -> bool: ...

    def IsValid(self) -> bool: ...

    def MightHaveChildren(self) -> bool: ...

    def Persist(self) -> bool: ...

    def SetData(self, data: SBData, error: SBError) -> bool: ...

    def SetFormat(self, format: int) -> bool: ...

    def SetPreferDynamicValue(self, use_dynamic: int): ...

    def SetPreferSyntheticValue(self, use_synthetic: bool): ...

    def SetSyntheticChildrenGenerated(self, arg2: bool): ...

    def SetValueFromCString(self, value_str: str, error: SBError = None) -> bool: ...

    def TypeIsPointerType(self) -> bool: ...
